name: deploy-argo-production

on:
  push:
    branches:
      - main

permissions:
    contents: write
    id-token: write
    packages: read

jobs:
    build-docker-image:
        uses: ./.github/workflows/build.yaml
        name: Build Docker image
        with:
            aws-role-arn: ${{ vars.PRODUCTION_ECR_ROLE_ARN }}
            docker_file_path: Dockerfile

    update-helm-values:
        name: Update Helm values
        runs-on: ubuntu-latest
        needs: build-docker-image
        env:
            ENVIRONMENT: 'production'
            REPOSITORY: ${{ github.event.repository.name }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Checkout helm config Repository
              uses: actions/checkout@v4
              with:
                  repository: Kittl/development-applications-config
                  ref: main
                  path: helm-config
                  token: ${{ secrets.GH_PAT }}
                  persist-credentials: false
            - name: Update Image Version in the related HelmChart values.yaml
              uses: fjogeleit/yaml-update-action@v0.14.0
              with:
                  valueFile: ${{ format('{0}/{1}/values.yaml', env.ENVIRONMENT, env.REPOSITORY) }}
                  propertyPath: 'deployment.image.tag'
                  value: ${{ needs.build-docker-image.outputs.image-tag }}
                  repository: Kittl/development-applications-config
                  branch: main
                  createPR: false
                  message: 'Update Image Version to ${{ needs.build-docker-image.outputs.image-tag }}'
                  token: ${{ secrets.GH_PAT }}
                  workDir: helm-config
